### PR TITLE
Importing files from parent directory

### PR DESCRIPTION
**Pull request by Acconut**
This is my first attempt at a bigger feature for lily. This PR allows the `..` and `.` token in import paths. These tokens can be used to access the parent directory or the current directory, as can be seen in the newly added test file (not yet integrated in the other proper tests). ~~I used the three dots (instead of the usual two dots for paths) because I wasn't sure how to add a new token in the beginning but this can be changed now.~~ In order to achieve this, I rewrote the scanner for the import path, I hope it's still understandable without comments.

This patch is still in the beginning (e.g. ~~the direct call to malloc without freeing~~ and the missing comments) but I wanted to show you this and get feedback if this is a route that you want to go at all. Also, two tests are failing because of wrong line numbers in exceptions :)

### CODE REVIEW

**Comment by FascinatedBox** [comment]
Gonna be leaving soon, but before that, I like some of this.

I'd rather have two dots instead of three for paths, so that it's consistent with what people use for command line/shell.

Rewriting the lexer is a-okay. I really want paths to be 'whole'. No like `import x / .. y .. ` kind of code.

I think that importing needs to, at some point, understand that the first module of a package is a root, and use that knowledge to base future imports off of. Something like 'try the current package, then the root package'. More on that later.

I like adding '..' because it opens up using parent directories. A single dot is okay for consistency.

I'm planning to finish off 1.2 on the 10th of October. I'd rather see this in 1.3 so that there's plenty of time to play around with it.

Overall, yeah. I'll take a deeper look at it soon.

**Comment by Acconut** [comment]
> I'd rather have two dots instead of three for paths, so that it's consistent with what people use for command line/shell.

Of course, I just used the three dots in the beginning because the token was already available. In the meantime I added a `..` token.

> I really want paths to be 'whole'. No like import x / .. y .. kind of code.

Good catch, I believe my rewrite allows these spaces. However, it may be beneficial to scan the import path as a string (e.g. `import "../views/login"`) which makes parsing easier and also if the name of a file/directory contains a space which is allowed.

> I think that importing needs to, at some point, understand that the first module of a package is a root, and use that knowledge to base future imports off of. Something like 'try the current package, then the root package'. More on that later.

Frankly, I am not a huge fan of this. I believe this method may be confusing and ambiguous and could lead to importing issues of you have multiple entry files in different locations.

> I'm planning to finish off 1.2 on the 10th of October. I'd rather see this in 1.3 so that there's plenty of time to play around with it.

Sure, no problem :)

**Comment by FascinatedBox** [comment]
I'm wary of using string literals for paths. It opens up the gate not just to spaces in filenames, but also to usage of escape characters. So now it's possible to import a file that's a bunch of gibberish in its name plus a sane prefix. That and it's something that looks like a string literal even though it really isn't (so it's not possible to call methods/etc. on it).

As far as the import idea, there'd be a max of two roots at any one time: The first module loaded, and whatever is a current root. It might seem bad, but it's necessary for, say, being able to import a package "installed" by garden that's more than a single module. The imports in that package need to be run as they normally are.

**Comment by Acconut** [comment]
Sounds good :+1:

**Comment by FascinatedBox** [comment]
I originally planned on pulling this in early 1.3, but got sucked into keyword arguments. Now I'm not so sure about merging this. I've quite a different idea of how to implement this now, which makes me skeptical of pulling this. I hate to have asked you to do extra only to end up saying no. Sorry about that.

**Comment by Acconut** [comment]
No problem, please don't apologize. I am more interested in getting this language forward than just having my PRs merged :) Your proposal in #347 looks very promising and I am looking forward to its development.

**Pull request closed without merging**
